import { Brain, Users, BookOpen } from "lucide-react";

function Stats() {
  const stats = [
    {
      icon: <Brain size={40} />,
      title: "AI Powered",
      desc: "Personalized roadmaps generated by AI",
    },
    {
      icon: <BookOpen size={40} />,
      title: "Learning Paths",
      desc: "Structured paths for every goal",
    },
    {
      icon: <Users size={40} />,
      title: "Career Focused",
      desc: "Built for students and professionals",
    },
  ];

  return (
    <section className="bg-slate-950 px-6 py-20">
      <div className="mx-auto max-w-7xl">
        <div className="grid gap-8 md:grid-cols-3">
          {stats.map((item) => (
            <div
              key={item.title}
              className="rounded-3xl border border-slate-800 bg-slate-900 p-8 text-center text-white"
            >
              <div className="mb-5 flex justify-center text-violet-400">
                {item.icon}
              </div>

              <h3 className="mb-3 text-2xl font-bold">
                {item.title}
              </h3>

              <p className="text-slate-400">
                {item.desc}
              </p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

export default Stats;